### ISSUE TITLE
AUTH not working 

### ISSUE THREAD

**Issue by nahidhasan141400** [yeasin2002/TaskHub#2]
![image](https://github.com/Mdkawsarislam2002/TaskHub/assets/63138743/626a4111-a257-421b-a0c6-b27423be13c4)
I'm login to the website but not able to create any todo 

just test issues

**Comment by Mdkawsarislam2002** [comment]
Thanks for the issue 
unfortunately, Projects is not completed yet.

**Comment by Mdkawsarislam2002** [comment]
Thanks for your contribution. We fixed this problem.
Try again and share your feedback. 

- Yeasin
